environments:
  onprem:
    description: On-premises Exadata estate
    ssh_user: al44002
    auth:
      method: password
      sudo: true
      sudo_password: same_as_ssh
  oci:
    description: OCI Exadata estate
    ssh_user: AN697937AD
    auth:
      method: password
      sudo: true
      sudo_password: same_as_ssh

clusters:
  - name: onprem-rac01
    environment: onprem
    hosts:
      - name: dc04dx26db01
        address: dc04dx26db01.internal.das
      - name: dc04dx26db02
        address: dc04dx26db02.internal.das
  - name: iad3dx02v2-mqj1
    environment: oci
    hosts:
      - name: iad3dx02v2-mqj101
        address: iad3dx02v2-mqj101.east.ockyn.internal.das
      - name: iad3dx02v2-mqj102
        address: iad3dx02v2-mqj102.east.ockyn.internal.das

collection:
  output_dir: output
  ssh:
    port: 22
    timeout_seconds: 60
    strict_host_key_checking: accept-new
